server:
  port: 8081

spring:
  application:
    name: user-service
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_NAME}
    password: ${DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_APP_USERNAME}
    password: ${GOOGLE_APP_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


app:
  jwt:
    secret: your_very_long_and_secret_key_22130260_thanh_nlu
    expiration: 86400000