server:
  port: 8083

spring:
  application:
    name: COURSE-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/db_course
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/