@startuml
skinparam defaultTextAlignment center
start
:Giảng viên chọn lớp học phần;
:Truy cập module "Ngân hàng câu hỏi";
if (Hành động?) then ([Thêm câu hỏi])
  :Import từ tệp Excel hoặc nhập tay;
  :Cấu hình đáp án, mức độ khó và gắn CLO;
  :Lưu vào kho câu hỏi;
else ([Tạo đề thi])
  :Nhập cấu hình Ma trận đề thi (Số lượng, Mức độ, CLO);
  :Hệ thống lấy ngẫu nhiên câu hỏi từ kho;
  if (Đủ câu hỏi theo ma trận?) then (Thiếu)
    :Cảnh báo không đủ câu hỏi trong kho;
    detach
  else (Đủ)
    :Hệ thống sinh đề thi;
    :Giảng viên lưu & xuất bản đề thi;
  endif
endif
stop
@enduml