server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # 1. USER SERVICE
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/**
          filters:
            - name: JwtAuthenticationFilter

        # 2. COURSE SERVICE
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/course-service/**
          filters:
            - name: JwtAuthenticationFilter

        # 3. RUBRIC SERVICE
        - id: rubric-service
          uri: lb://RUBRIC-SERVICE
          predicates:
            - Path=/api/v1/rubrics/**
          filters:
            - name: JwtAuthenticationFilter



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jwt:
  secret: ${SECRET_KEY}